name 'puppetlabs-git'
version '0.0.2'

author 'puppetlabs'
license 'Apache 2.0'
project_page 'https://github.com/puppetlabs/puppetlabs-git/'
source 'git://github.com/puppetlabs/puppetlabs-git.git'
summary 'module for installing git'
description 'module for installing git'
